# Generated by Django 5.0.6 on 2024-05-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feisbucc', '0004_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='feisbucc.profile'),
        ),
    ]
