# Generated by Django 5.0.6 on 2024-05-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feisbucc', '0007_alter_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_post',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
